### ISSUE TITLE
I can't create a backdoor. 

### ISSUE THREAD

**Issue by XxXUnknown** [oddcod3/Phantom-Evasion#12]
Can somebody help me ?
My problem is:
When I open the phantom evasion, two problems appear,  the first problem says: [>] Package libc6-dev-i386 [Not found]. And the second says: [Wine] Python not found.
and I press Enter twice, because the same error appears again, then the program opens apparently normal, but when I finish creating the back door, an error appears, and the backdoor is not created.
Help me please, I can not create a back door.
NOTE: I downloaded the latest version of python (version 3).
PHOTOS:
https://ibb.co/dRfYno: first error
https://ibb.co/ezwv08: second error

**Comment by oddcod3** [comment]
Python 3 compatibility is temporarily suspended as mentioned in the README (install python 2.7).
In order to use wine-pyinstaller modules you need to manually install python and pyinstaller in wine

**Comment by XxXUnknown** [comment]
Ok I will try it.

**Comment by XxXUnknown** [comment]
Should I uninstall python 3 ? Or I install python  2 normally?

**Comment by XxXUnknown** [comment]
I installed python 2.7.15, but the problems appear again, can u say me how to install python and pyinstaller in wine pls :/.
Any video ?

**Comment by XxXUnknown** [comment]
I installed Python and pyinstaller correctly, but now I have the second error, when I open phantom-evasion appear this : Package libc6-dev-i386. That message appear in red,but the phantom-evasion open apparently normal, buy when I finish to create the backdoor appear the second error, I think that the errors are connected.
Pictures: 
Error 1 : https://ibb.co/fsYuTT
Error 2 : https://ibb.co/heB3No

**Comment by XxXUnknown** [comment]
I tried that , but appear the same error :/. 
When I was searching the answer, I read that I can't install that package because my pc is 32 bits, or something like that.

**Comment by XxXUnknown** [comment]
Okay I will try it.

**Comment by usama7628674** [comment]
@XxXUnknown You can install metasploit using `apt install --reinstall metasploit-framework`

**Comment by XxXUnknown** [comment]
Okay i'm going do that.

**Comment by XxXUnknown** [comment]
update kali linux, reinstall phantom-evasion but it's still useless, and when I try to reinstall metasploit-framework appear error that say me : --reinstall doesn't make sense, or something like that.i will try it again.
