### ISSUE TITLE
Consider removing Monero Miner.

### ISSUE THREAD

**Issue by NullArray** [oddcod3/Phantom-Evasion#2]
As part of the automatic setup and dependency check, Phantom-Evasion installs `xmr-stak` Monero crypto currency miner. I know you mention as much in the README of the repository but simply installing it and turning it on by default seems disingenuous at best and actively malicious at worst.

If you insist on including the miner, i think more transparency with regards to this would be beneficial. I would suggest that after running the setup procedure and installing all the dependencies required by the tool you prompt the user and ask something along the lines of:

> In order to support the developer of this tool/framework, you can help out by allowing the program to install a Monero Miner along side the program's main functionality. The miner will be configured to use a low amount of system resources and can be deactivated at any time should you wish to do so.

Then clearly ask the user whether they agree to this or not. If they agree, great, if they don't, don't call the function and related operations in the `Phantom_lib.py` file and simply provide the core functionality of Phantom-Evasion as is.

Just my two cents.

**Comment by oddcod3** [comment]
I'll provide to advise the final user in a clearer way in the next days 
By the way i let you notice that mining is already (since it was included the first time) not mandatory.
You can simply stop the miner by default changing Miner = False in the config file inside Donate folder (as mentioned in the  readme Donate section) 
Thank you for sharing your opinion

**Comment by NullArray** [comment]
No problem, and thank you for the consideration. I appreciate the work you've done with regards to this tool. Allowing the user to opt-out before the miner is installed is beneficial in general, since it fosters more trust between you and your users and will be beneficial in terms of credibility as well.

**Comment by oddcod3** [comment]
I've updated phantom evasion and now users can opt-out before miner installation.
I also used your example message pratically unchanged.
Thank you again for the advice

**Comment by NullArray** [comment]
Thanks, keep up the good work!
