### ISSUE TITLE
Unable to open resigned.apk

### ISSUE THREAD

**Issue by xmagickx** [oddcod3/Phantom-Evasion#20]
Everything runs fine except when trying to resign the apk... It gives output unable to open resigned.apk as zip archive... Caused by java.lang.ClassNotFoundException: sun.misc.BASE64Encoder.

**Comment by usama7628674** [comment]
@xmagickx see #19

**Comment by xmagickx** [comment]
I'm not getting that output because I already have that resigned_apk.jar in
my latest phantom-evasion... Instead I'm getting this...


On 28-Jun-2018 6:52 PM, "Usama Abdul Sattar" <notifications@github.com>
wrote:

@xmagickx <https://github.com/xmagickx> see #19
<https://github.com/oddcod3/Phantom-Evasion/issues/19>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/oddcod3/Phantom-Evasion/issues/20#issuecomment-401032594>,
or mute the thread

**Comment by usama7628674** [comment]
@oddcod3 But it needs work as @oddcod3 said in #19

**Comment by oddcod3** [comment]
Yes as @usama7628674  said Android and osx modules need to be reworked (future release 1.2) @xmagickx
