### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by usama7628674** [oddcod3/Phantom-Evasion#24]
Please add 32 bit and 64 bit `windows/meterpreter/reverse_https polymorphic stager` as tcp and http are easily detected by windows defender.

**Comment by oddcod3** [comment]
Using windows modules number 9 or 10 (with strip executable) actually works for me 🤔
Have you tried thoose new modules?

**Comment by usama7628674** [comment]
So those modules act as rev_https.

**Comment by usama7628674** [comment]
@christomitov You mean rev_http and rev_tcp

**Comment by christomitov** [comment]
@usama7628674 I mean none of the payloads in the list bypass Windows Defender at all for me.

**Comment by usama7628674** [comment]
@oddcod3 That's why I said rev_https is alternative option to bypass windefender.

**Comment by oddcod3** [comment]
Added pure c reverse https stager (x86/x64) in Phantom-Evasion 2.0

**Comment by usama7628674** [comment]
@oddcod3 That's very nice of you.Thnaks
