### ISSUE TITLE
Mfsvenom payload gets detected after encoding!

### ISSUE THREAD

**Issue by xhazin** [oddcod3/Phantom-Evasion#34]
My payload is undetectable but my msfvenom meterpreter (windows/vncinject/reverse_tcp) get detected! I also encoded it with with x86/shikata_ga_nai + Triple Multibyte-key xor ..but soon as the meterpreter session opens , windows detect it and he kills it.

**Comment by leiferdjango** [comment]
detected by: which AV?
did you scan your payload file to **virustotal**?

**Comment by xhazin** [comment]
it's detected by windows defender. No i didn't scan it.
![meterpreter error](https://user-images.githubusercontent.com/43448226/45944185-24c16100-bfe1-11e8-91dd-188e179e2501.jpg)

**Comment by xhazin** [comment]
it's detected by windows defender. No i didn't scan it.
![meterpreter error2](https://user-images.githubusercontent.com/43448226/45944243-533f3c00-bfe1-11e8-93e0-4dbb7a4b00a7.jpg)

**Comment by leiferdjango** [comment]
seems your sysyem detect it as threat posibly beacuse an update or security patch, in this case you have to use another payload, that one is no longer undectable in your system

**Comment by xhazin** [comment]
it's a bit ridiculous to say this but i'm about to hack a pc with windows 98 operating system. Will i get detected with this method if he has AV?
