### ISSUE TITLE
Problem Installing Phantom

### ISSUE THREAD

**Issue by slightlybent1** [oddcod3/Phantom-Evasion#36]
I am missing somthing because i cant seem to install this onto my machine.
Could you please help?

![ss](https://user-images.githubusercontent.com/44589804/47686736-1b647f00-dbb3-11e8-8d8f-7de5eae640bc.png)

My distro is not included in the "Compatible, but ParrotSec is a Kali-based Pen Testing.
I'm just confused as to install the needed modules. I tried "sudo apt install -f", but no help.
Please and thank you.

UPDATE:
I tried this method, but got the same results.
Install both 2.7 versions.
https://superuser.com/questions/328216/install-python-pywin32-in-wine

**Comment by dmcxblue** [comment]
I had the same issue but just ignored and the tool still functions, what an amazing tool but people uploading to VirusTotal just messes open source tools like these up man pff but anyway awesome tool

**Comment by slightlybent1** [comment]
Familiar with veil? Pyinstaller won't install for some reason. Otherwise great app. Suggestions?

**Comment by oddcod3** [comment]
Fixed in Phantom-Evasion 2.0!

**Comment by slightlybent1** [comment]
it seems to have fixed itself, i had to run the auto-installer 3 times, but it worked.
