### ISSUE TITLE
using stageless payloads make phantom evasion crash

### ISSUE THREAD

**Issue by phra** [oddcod3/Phantom-Evasion#38]
hi,

if you select a stageless payload, such as `windows/x64/meterpreter_reverse_https`, phantom-evasion will crash during the XOR encryption with the following error:

`OSError: [Errno 7] Argument list too long`

probably the stageless payload is bigger than ARGV argument size limit.

**Comment by oddcod3** [comment]
Fixed in Phantom-Evasion 2.0
