### ISSUE TITLE
Support OSX

### ISSUE THREAD

**Issue by evandrix** [oddcod3/Phantom-Evasion#41]
it is possible, i have done it on my own copy, e.g. `mingw-w64` `osslsigncode` can be `brew install`ed + you can detect OSX via `platform.system() == "Darwin"`

**Comment by oddcod3** [comment]
OSX support has been delayed for long time   due to laziness/other features priority 😅
I will try to include OSX support in the next release and i will notify that in this open issue!

**Comment by evandrix** [comment]
ok, tyvm!
