### ISSUE TITLE
Wine Environment Check fails after second run

### ISSUE THREAD

**Issue by infosecconsultant** [oddcod3/Phantom-Evasion#51]
Hi All,

Spun up a brand new Kali install:

> Linux 4.19.0-kali3-amd64 #1 SMP Debian 4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux

Then performed the following actions to spin up the environment:
```
git clone https://github.com/oddcod3/Phantom-Evasion.git
cd Phantom-Evasion
chmod u+x phantom-evasion.py
python3 phantom-evasion.py

```
This worked fine, I generated a payload, seems to work. 
Gracefully quit the application. 

Upon attempting to relaunch the application I'm hitting the following error at the Wine Environment Check: 
```
[>] Python Version: 3.6.8

[>] Kali-Rolling Detected!!

[>] Checking dependencies:

[>] Package libc6-dev-i386               [Found]

[+] apktool                              [Found]
[+] apktool.jar file                     [Found]
[+] gcc                                  [Found]
[+] mingw-w64                            [Found]
[+] pyinstaller                          [Found]
[+] apksigner                            [Found]
[+] metasploit-framework                 [Found]
[+] strip                                [Found]
[+] osslsigncode                         [Found]
[+] Wine Environment check
Traceback (most recent call last):
  File "phantom-evasion.py", line 709, in <module>
    Phantom_lib.dependencies_checker()
  File "Setup/Phantom_lib.py", line 296, in dependencies_checker
    kali_parrot_isready()
  File "Setup/Phantom_lib.py", line 204, in kali_parrot_isready
    wine_check()
  File "Setup/Phantom_lib.py", line 510, in wine_check
    if "cannot find" in py_check:
TypeError: a bytes-like object is required, not 'str'
```

Can't seem to get past this and not sure what the actual issue here is.
Any help would be appreciated. 

Cheers,

**Comment by infosecconsultant** [comment]
Okay. Quick and dirty fix, the issue seems to be with reading and writing the files as binary and non binary
If you check the Setup/Config.txt file and it says WinEnv=OK that means it's been set up and should be working correctly. 

You've manually done the following check.

```
def wine_fastcheck():
    wine=False
    wineok = open("Setup/Config.txt","r")
    for line in wineok:
        if "WinEnv=OK" in line:
            wine=True
    return wine
```

So simply comment out the rest set the value wine as true

```def wine_fastcheck():

    #wine=False
    #wineok = open("Setup/Config.txt","r")
    #for line in wineok:
    #    if "WinEnv=OK" in line:
    #        wine=True
    wine=True
    return wine
```

Hope that helps someone else

**Comment by matineit** [comment]
I also get this error while i executed : python3 phantom-evasion.py

[+] Wine Environment check
Traceback (most recent call last):
  File "phantom-evasion.py", line 709, in <module>
    Phantom_lib.dependencies_checker()
  File "Setup/Phantom_lib.py", line 296, in dependencies_checker
    kali_parrot_isready()
  File "Setup/Phantom_lib.py", line 204, in kali_parrot_isready
    wine_check()
  File "Setup/Phantom_lib.py", line 510, in wine_check
    if "cannot find" in py_check:
TypeError: a bytes-like object is required, not 'str'

Below is my Config.txt file :
WinEnv=Check
Miner=Installed

Mining=True
Username=2jney0sk2w3e199

**Comment by 532609499** [comment]
same problem with you but  the config.txt is WinEnv=Check

**Comment by 532609499** [comment]
flowing with this man 
```
#wine=False
    #wineok = open("Setup/Config.txt","r")
    #for line in wineok:
    #    if "WinEnv=OK" in line:
    #        wine=True
    wine=True
    return wine
```
it works, thanks bro

**Comment by infosecconsultant** [comment]
No worries. Further searching of that error message suggests it's something to do with the files being either written or read as 'binary' instead of plain text (using rb/wb/r/w switches for open("Setup/Config.txt","*")

**Comment by praveen25111997** [comment]
Traceback (most recent call last):
  File "phantom-evasion.py", line 716, in <module>
    Phantom_lib.xmr_miner()
  File "Setup/Phantom_lib.py", line 775, in xmr_miner
    subprocess.call(['tmux','send-keys','-t','phantom-miner','\"\x03\"','C-m'], stdout=open(os.devnull,'wb'), stderr=open(os.devnull,'wb'))
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
![Screenshot from 2019-07-10 17-30-58](https://user-images.githubusercontent.com/40700681/60967525-81a3c300-a338-11e9-9f96-2dd2ff1c0f96.png)
![Screenshot from 2019-07-10 17-30-58](https://user-images.githubusercontent.com/40700681/60967533-89fbfe00-a338-11e9-8764-740d22b59e44.png)

**Comment by Honey-Pots-0** [comment]
**cd Setup**
**leafpad Config.txt**
and select all text and paste it


    #wine=False
    #wineok = open("Setup/Config.txt","r")
    #for line in wineok:
    #    if "WinEnv=OK" in line:
    #        wine=True
    wine=True
    return wine

**Comment by bitarbe** [comment]
first of all i face same problem and i do 
apt-get upgrade then i go to config.txt modified to be 

WinEnv=Check
Miner=Installed
#wine=False
#wineok = open("Setup/Config.txt","r")
#for line in wineok:
#    if "WinEnv=OK" in line:
#        wine=True
wine=True
return wine


its works

**Comment by catekuser** [comment]
> Okay. Quick and dirty fix, the issue seems to be with reading and writing the files as binary and non binary
> If you check the Setup/Config.txt file and it says WinEnv=OK that means it's been set up and should be working correctly.
> 
> You've manually done the following check.
> 
> ```
> def wine_fastcheck():
>     wine=False
>     wineok = open("Setup/Config.txt","r")
>     for line in wineok:
>         if "WinEnv=OK" in line:
>             wine=True
>     return wine
> ```
> 
> So simply comment out the rest set the value wine as true
> 
> ```
> 
>     #wine=False
>     #wineok = open("Setup/Config.txt","r")
>     #for line in wineok:
>     #    if "WinEnv=OK" in line:
>     #        wine=True
>     wine=True
>     return wine
> ```
> 
> Hope that helps someone else

works great, thank you!

**Comment by gallant15** [comment]
after inputing all this command
git clone https://github.com/oddcod3/Phantom-Evasion.git
cd Phantom-Evasion
chmod u+x phantom-evasion.py
python3 phantom-evasion.py
instead it should detect kali rolling automatically it shows
MAIN MENU
1. Window Modules  2.Linux Modules 3. Android Modules 4. Persistance Module etc 
i dont the options top choose, after taking option 2 itsask for password
![Screenshot_2020-04-29_16-48-26](https://user-images.githubusercontent.com/64376672/80657753-65feda00-8a7c-11ea-8c94-379330e0649a.png)
![Screenshot_2020-04-29_16-48-26](https://user-images.githubusercontent.com/64376672/80657765-6bf4bb00-8a7c-11ea-9a46-4e68e42c06a3.png)

**Comment by gallant15** [comment]
after chosing windows modules it display 
![Screenshot_2020-04-29_17-01-34](https://user-images.githubusercontent.com/64376672/80658543-4cf72880-8a7e-11ea-93e6-f62410379b8b.png)
