### ISSUE TITLE
Can't run phantom-evasion.py

### ISSUE THREAD

**Issue by Hyperscope35** [oddcod3/Phantom-Evasion#52]
getting this error when I tried to run phantom-evasion.py (tried executing with both python and ./ command) Sorry if im just retarded, im a beginner.

Error:

Traceback (most recent call last):
  File "./phantom-evasion.py", line 32, in <module>
    import Phantom_lib
  File "Setup/Phantom_lib.py", line 28, in <module>
    from OpenSSL import crypto
ImportError: No module named OpenSSL

**Comment by infosecconsultant** [comment]
You need to submit more information. What OS. What version? 
You are missing the OpenSSL library for python.

These instructions will hopefully help:

https://stackoverflow.com/questions/9001316/how-to-install-openssl-for-python

**Comment by infosecconsultant** [comment]
Googling "ImportError: No module named OpenSSL" should guide you along otherwise.

**Comment by Hyperscope35** [comment]
Thanks a lot! Even after I had installed OpenSSL I got some small errors but luckily I managed to fix them myself. The main part I needed help with was OpenSSL and thanks to you I got Phantom-evasion working now ^^.

Thanks!
