### ISSUE TITLE
/usr/share/metasploit-framework/lib/msf/core/payload/uuid.rb:356:in `to_uri': undefined method `encode_base64url' for Rex::Text:Module (NoMethodError)

### ISSUE THREAD

**Issue by gearcapitan** [oddcod3/Phantom-Evasion#6]
![kali_linux-2018-04-03-19-42-25](https://user-images.githubusercontent.com/13740942/38282696-2cbf4c84-3777-11e8-92fd-04c7e2c1bdb2.png)

**Comment by oddcod3** [comment]
Hi gearcapitan i can't reproduce your issue (i get no error using windows/x64/meterpreter/reverse_https)
Which module of phantom evasion have you used? 
OS version and architecture?

**Comment by gearcapitan** [comment]
i tray again with this payload but i have same error
windows/meterpreter/reverse_https

**Comment by oddcod3** [comment]
the issue is related to msfvenom update
https://github.com/rapid7/metasploit-framework/issues/9810
