### ISSUE TITLE
wine not found python and pyinstallier

### ISSUE THREAD

**Issue by gearcapitan** [oddcod3/Phantom-Evasion#7]
I have perfectly installed Veil

![kali_linux-2018-04-03-20-13-08](https://user-images.githubusercontent.com/13740942/38283414-88fb6dee-377b-11e8-8a1e-be6e62fc9118.png)
![kali_linux-2018-04-03-20-13-22](https://user-images.githubusercontent.com/13740942/38283415-89167ae4-377b-11e8-902b-58fa7cedf7e1.png)

**Comment by Anon-65535** [comment]
Same Problem....how can I solve it?

**Comment by oddcod3** [comment]
Open a terminal:

sudo dpkg --add-architecture i386
sudo apt-get update 
sudo apt-get install wine32

Run Winecfg

Download python2.7.14.msi installer from python official website

Run msiexec /i python2.7.14.msi  (install for all user)

Install pip on wine

Run wine python -m pip install pyinstaller 

That's all

**Comment by gearcapitan** [comment]
i cant push netx!!!
![kali_linux-2018-04-09-12-26-07](https://user-images.githubusercontent.com/13740942/38512613-48e5cd06-3bf1-11e8-8fca-e53853c5dbf7.png)

![kali_linux-2018-04-09-12-26-01](https://user-images.githubusercontent.com/13740942/38512612-48c8eb6e-3bf1-11e8-8d15-17ef639b7ac3.png)

**Comment by gearcapitan** [comment]
other error, ended prematurely
![kali_linux-2018-04-09-13-07-26](https://user-images.githubusercontent.com/13740942/38514491-f9a57ea2-3bf6-11e8-8b32-94e9117a1d2a.png)

**Comment by Anon-65535** [comment]
Can't install python2.7.14.msi, it doesn't anything with this command....
How can I solve it?

**Comment by oddcod3** [comment]
@Anon-65535 
Have you executed msiexec /i python 2.7.14.msi on terminal?

**Comment by Anon-65535** [comment]
Yes, it has not any kind of resoult.
The installer window doesn't appear...
I have Kali Rolling 2018.1

**Comment by oddcod3** [comment]
I've experienced this problem once 
try to execute 
wine msiexec /i python 2.7.14.msi ALLUSER=1

**Comment by Anon-65535** [comment]
Nothing to do!!
In your first post where you wrote Winecfg, did you mean winecfg?
If the answer is yes why i have to do it?

**Comment by Anon-65535** [comment]
I have found the solution....

dpkg --add-architecture i386
apt-get update
apt full-upgrade

Then
Download the Python 2.7.13 MSI installer, the x86 version!!

Then 
wine msiexec /i python 2.7.13.msi
Next -> Next -> Install for all users

Then
wine python -m pip install pyinstaller

Now you can use Phantom Evasion without any problems!

Bye, I hope it's helpful!

**Comment by UN5T48L3** [comment]
@Anon-65535 It doesnt work for me. How can we fix it?

**Comment by Anon-65535** [comment]
> @Anon-65535 It doesnt work for me. How can we fix it?

What is teh problem?
