### ISSUE TITLE
AttributeError: module 'OpenSSL.crypto' has no attribute 'PKCS12Type'

### ISSUE THREAD

**Issue by boxyvision** [oddcod3/Phantom-Evasion#77]
Hi,
Anyone can help me to fix my issue ?

[>] Sign Executable 

Traceback (most recent call last):
  File "phantom-evasion.py", line 396, in <module>
    Phantom_lib.CmdlineLauncher(sys.argv)
  File "Setup/Phantom_lib.py", line 1309, in CmdlineLauncher
    ModuleLauncher(M_type,ModOpt)
  File "Setup/Phantom_lib.py", line 964, in ModuleLauncher
    ExeSigner(ModOpt["Outfile"],ModOpt["SpoofCert"],ModOpt["descr"])
  File "Setup/Phantom_lib.py", line 439, in ExeSigner
    pfx = crypto.PKCS12Type()
AttributeError: module 'OpenSSL.crypto' has no attribute 'PKCS12Type'

**Comment by 0XAXSDD** [comment]
我也是这个问题

**Comment by benkhouya** [comment]
Same here!

**Comment by anonymous187** [comment]
> Hi,
> Anyone can help me to fix my issue ?
> 
> [>] Sign Executable
> 
> Traceback (most recent call last):
> File "phantom-evasion.py", line 396, in
> Phantom_lib.CmdlineLauncher(sys.argv)
> File "Setup/Phantom_lib.py", line 1309, in CmdlineLauncher
> ModuleLauncher(M_type,ModOpt)
> File "Setup/Phantom_lib.py", line 964, in ModuleLauncher
> ExeSigner(ModOpt["Outfile"],ModOpt["SpoofCert"],ModOpt["descr"])
> File "Setup/Phantom_lib.py", line 439, in ExeSigner
> pfx = crypto.PKCS12Type()
> AttributeError: module 'OpenSSL.crypto' has no attribute 'PKCS12Type'

I am having the same issue, any help??

**Comment by Txoka** [comment]
Changing:
```
pfx = crypto.PKCS12Type()
```
to
```
try:
    pfx = crypto.PKCS12()
except AttributeError:
    pfx = crypto.PKCS12Type()
```
in Exesigner function in the file "/Setup/Phantom_lib.py" solves the signing error.
(At least for me)

**Comment by ayashgupta** [comment]
It didn't worked, anyone else has any solution for this? I typed what Txoka said in the setup/Phantom_lib.py and it made the program to even stop working. 
developer?

**Comment by Txoka** [comment]
Please add log of ur error.

**Comment by 2igzpeter** [comment]
HI! 
I have a problem. 
name 'crypto' is not defined!

I have this on code:
from OpenSSL import crypto

console error:

/////////////////////////////////////////////////////////////////////////////////////////////////////////
File "phantom-evasion.py", line 401, in <module>
    CompleteMenu()
  File "phantom-evasion.py", line 124, in CompleteMenu
    Phantom_lib.ModuleLauncher(module_type)
  File "Setup/Phantom_lib.py", line 963, in ModuleLauncher
    ExeSigner(ModOpt["Outfile"],ModOpt["SpoofCert"],ModOpt["descr"])
  File "Setup/Phantom_lib.py", line 424, in ExeSigner
    x509 = crypto.load_certificate(crypto.FILETYPE_PEM, online_cert)
NameError: name 'crypto' is not defined

////////////////////////////////////////////////////////////////////////////////////////////////////////////


someone can u help me?
thx

**Comment by FoxSinOfGreed1729** [comment]
> Changing:
> 
> ```
> pfx = crypto.PKCS12Type()
> ```
> 
> to
> 
> ```
> try:
>     pfx = crypto.PKCS12()
> except AttributeError:
>     pfx = crypto.PKCS12Type()
> ```
> 
> in Exesigner function in the file "/Setup/Phantom_lib.py" solves the signing error.
> (At least for me)

This worked for me. Excellent Idea man. Created an account just to thank you for your help.

**Comment by FoxSinOfGreed1729** [comment]
Try installing openssl
 sudo pip install pyopenssl

**Comment by boxyvision** [comment]
> > Changing:
> > ```
> > pfx = crypto.PKCS12Type()
> > ```
> > 
> > 
> > to
> > ```
> > try:
> >     pfx = crypto.PKCS12()
> > except AttributeError:
> >     pfx = crypto.PKCS12Type()
> > ```
> > 
> > 
> > in Exesigner function in the file "/Setup/Phantom_lib.py" solves the signing error.
> > (At least for me)
> 
> This worked for me. Excellent Idea man. Created an account just to thank you for your help.

Worked for me too! 
Thank you!

**Comment by fortniterocks2** [comment]
File "/home/kali/Phantom-Evasion/phantom-evasion.py", line 27, in <module>
    import Phantom_lib
  File "Setup/Phantom_lib.py", line 439
    try:
TabError: inconsistent use of tabs and spaces in indentation
